# 数据集根目录
path: D:\Workspace\Projects\tyza66\YoloTrainDemo\datasets\animal
# 训练集文件
train: train\images
# 验证集文件
val: valid\images
# 测试集文件
test: test\images
# 类别名称
names:
  0: buffalo
  1: elephant
  2: rhino
  3: zebra
